### ISSUE TITLE
would be nice to merge improvements from https://github.com/zzaakiirr/confluence-markdown-exporter fork

### ISSUE THREAD

**Issue by tmotyl** [gergelykalman/confluence-markdown-exporter#11]
Just FYI, the fork:
https://github.com/zzaakiirr/confluence-markdown-exporter
Contains some nice improvements for the script. I think it would be good idea to incorporate at last some of them here.

**Comment by gergelykalman** [comment]
That fork is a bit old and I don't have the time to dig through everything right now.
However, if you wish to make pull requests that:
- are rebased to HEAD
- only contain one commit
- only have one feature/fix in them

I will take a look and merge them if it makes sense.

**Comment by tmotyl** [comment]
I'm grateful to you for making this script public :heart: 
I'm trying to be a good citizen and contribute in the way I would love others to contribute to my repos.
Of course, feel free to do whatever you like with these contributions. 
However, I'll use the https://github.com/zzaakiirr/confluence-markdown-exporter fork then, as it is free of most of the issues I reported here.

**Comment by gergelykalman** [comment]
You are free to use whatever you want as long as you keep the license. This I had to update to contain my proper name, but feel free to use the old one.

The reason I won't willy-nilly merge your code is because the quality is subpar and **your branch is dangerous to use**.

You have removed my sanitisation routine that turns .. in titles into harmless _! No idea why you did that, but now you are exposing every single user of your code to arbitrary file overwrites on their systems. Give a page a title of ../../../../../../../../tmp/hello and you will see what I'm talking about.
